### ISSUE TITLE
你好，数据现在是否可以下载呀？

### ISSUE THREAD

**Issue by m1231106** [SHU-FLYMAN/HDR-NET#2]
如题

**Comment by SHU-FLYMAN** [comment]
miaoyp9210
        您好！数据应该在本周更新，虽然论文还没有被接受。
        


2024-8-6
| |
曹建斌
|
|
***@***.***
|
---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2024年8月6日 12:36 |
| 收件人 | ***@***.***> |
| 抄送人 | ***@***.***> |
| 主题 | [SHU-FLYMAN/HDR-NET] 你好，数据现在是否可以下载呀？ (Issue #2) |

如题

**Comment by m1231106** [comment]
好滴，谢谢。

**Comment by zsl501** [comment]
你好，数据集是论文发表后才上传吗

**Comment by 66677785658565** [comment]
请问数据集什么时候能公布呢

**Comment by SHU-FLYMAN** [comment]
好的好的，我这两天整理

---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2024年10月28日 11:13 |
| 收件人 | SHU-FLYMAN/HDR-NET ***@***.***> |
| 抄送人 | 天涯居士 ***@***.***>,
Comment ***@***.***> |
| 主题 | Re: [SHU-FLYMAN/HDR-NET] 你好，数据现在是否可以下载呀？ (Issue #2) |

请问数据集什么时候能公布呢

**Comment by zbx-122** [comment]
期待啊，我们实验室做条纹投影，东西少，研究生只有研二快结束的时候可以碰到实验仪器（相机投影仪啥的），做深度学习的话有这个数据集可以验证很多东西了，感谢开源

**Comment by zbx-122** [comment]
期待啊，我们实验室做条纹投影，东西少，研究生只有研二快结束的时候可以碰到实验仪器（投影仪啥的），做深度学习的话有这个数据集可以验证很多东西了，感谢开源

**Comment by zbx-122** [comment]
期待啊，我们实验室做条纹投影，东西少，研究生只有研二快结束的时候可以碰到实验仪器（投影仪啥的），做深度学习的话有这个数据集可以验证很多东西了，感谢开源

**Comment by SHU-FLYMAN** [comment]
已经上传
